import test from 'node:test';import assert from 'node:assert/strict';
import {verifiedSelf,saveOwnName,requestOwnEmail,resetOwnPassword,signOutOwnSessions} from './selfAccount.js';
function fixture(){let user={id:'self',email:'self@example.invalid',user_metadata:{full_name:'Before',other:'retained'}};const calls=[];const client={auth:{getUser:async()=>({data:{user:structuredClone(user)}}),updateUser:async payload=>{calls.push(['update',payload]);if(payload.data)user.user_metadata={...user.user_metadata,...payload.data};if(payload.email)user.new_email=payload.email;return {data:{user}};},resetPasswordForEmail:async(...args)=>{calls.push(['reset',...args]);return {};},signOut:async options=>{calls.push(['signout',options]);return {};}},from:table=>({upsert:async(row)=>{calls.push(['profile',table,row]);return {};}})};return {client,calls};}
test('own profile saves canonical metadata and survives a fresh provider read',async()=>{const {client,calls}=fixture();const result=await saveOwnName(client,'self','  After  ');assert.equal(result.warning,'');const refreshed=await verifiedSelf(client,'self');assert.equal(refreshed.user_metadata.full_name,'After');assert.equal(refreshed.user_metadata.other,'retained');assert.deepEqual(calls[1],['profile','profiles',{id:'self',email:'self@example.invalid',full_name:'After'}]);});
test('a different session cannot mutate or send security emails',async()=>{for(const operation of [c=>saveOwnName(c,'other','Name'),c=>requestOwnEmail(c,'other','new@example.invalid','https://test.invalid'),c=>resetOwnPassword(c,'other','https://test.invalid'),c=>signOutOwnSessions(c,'other')]){const {client,calls}=fixture();await assert.rejects(operation(client),/session changed/);assert.equal(calls.length,0);}});
test('validation and backend errors never claim a successful save',async()=>{const {client,calls}=fixture();await assert.rejects(saveOwnName(client,'self',' '));await assert.rejects(requestOwnEmail(client,'self','invalid','https://test.invalid'));assert.equal(calls.length,0);client.auth.updateUser=async()=>({error:new Error('Provider unavailable')});await assert.rejects(saveOwnName(client,'self','After'),/Provider unavailable/);});
test('secure email change remains pending until provider confirms it',async()=>{const {client,calls}=fixture();const user=await requestOwnEmail(client,'self','new@example.invalid','https://test.invalid');assert.equal(user.email,'self@example.invalid');assert.equal(user.new_email,'new@example.invalid');assert.deepEqual(calls[0],['update',{email:'new@example.invalid'}]);});
test('reset uses verified current email and global signout uses provider scope',async()=>{const {client,calls}=fixture();await resetOwnPassword(client,'self','https://test.invalid');await signOutOwnSessions(client,'self');assert.deepEqual(calls,[['reset','self@example.invalid',{redirectTo:'https://test.invalid'}],['signout',{scope:'global'}]]);});
test('directory failure reports partial success without losing saved auth name',async()=>{const {client}=fixture();client.from=()=>({upsert:async()=>({error:new Error('denied')})});const result=await saveOwnName(client,'self','After');assert.match(result.warning,/directory/);assert.equal((await verifiedSelf(client,'self')).user_metadata.full_name,'After');});
