project_id = "mf-schema-baseline-84b36ad"
[api]
enabled = true
port = 55931
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 77
[db]
port = 55932
shadow_port = 55930
major_version = 15
[db.seed]
enabled = false
[studio]
enabled = false
[auth]
enabled = true
site_url = "http://127.0.0.1:5187"
additional_redirect_urls = ["http://127.0.0.1:5187"]
enable_signup = true
[auth.email]
enable_signup = true
enable_confirmations = false
[analytics]
enabled = false

[inbucket]
enabled = true
port = 55934
smtp_port = 55935
pop3_port = 55936
