-- STAGING ONLY. Restore exact effective source ACLs after Supabase bootstrap defaults.
BEGIN;
REVOKE ALL ON FUNCTION marginflow.current_auth_user_id() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.admin_invite_internal_staff(p_email text, p_full_name text, p_role_key text, p_permission_overrides jsonb) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.admin_update_internal_staff(p_user_id uuid, p_role_key text, p_status text, p_permission_overrides jsonb) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.admin_update_subscription(p_company_id uuid, p_status text, p_plan_slug text, p_trial_ends_at timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.archive_legacy_recovery_v1(p_company_id uuid, p_location_id uuid, p_products jsonb, p_invoices jsonb) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.begin_customer_onboarding(p_company_name text, p_country_code text, p_country_name text, p_language text, p_currency text, p_timezone text, p_default_vat numeric, p_week_starts_on text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.can_access_feature(target_company_id uuid, target_feature_key text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.can_access_profile(target_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.can_manage_company_features(target_company_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.claim_internal_staff_invite() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.close_support_workspace(target_session_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.company_has_no_members(target_company_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.company_subscription_allows_write(target_company_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.complete_customer_onboarding(p_company_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.create_company_with_owner(company_name text, location_name text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.current_workforce_employee_id(target_company_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.forget_supplier_product_learning(p_company_id uuid, p_location_id uuid, p_supplier_id uuid, p_mapping_id uuid, p_normalized_supplier_product_code text, p_normalized_supplier_description text, p_normalized_unit_of_measure text, p_normalized_pack_size text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.get_admin_audit_log(p_company_id uuid, p_actor_id uuid, p_action text, p_from timestamp with time zone, p_to timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.get_admin_companies(p_search text, p_status text, p_plan text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.get_admin_company_detail(target_company_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.get_admin_overview() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.get_admin_plans() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.get_admin_staff() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.get_customer_onboarding_state(p_company_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.get_effective_company_access(target_company_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.get_internal_admin_context() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.has_internal_permission(target_permission_key text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.has_workforce_permission(target_company_id uuid, target_permission_key text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.invoice_business_fingerprint_v1(p_invoice jsonb) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.is_active_company_member(target_company_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.is_company_feature_beta_eligible(target_company_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.is_company_owner(target_company_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.is_customer_onboarding_owner(target_company_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.is_internal_staff() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.is_platform_owner() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.is_support_workspace_scope(target_company_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.marginflow_first_numeric(p_payload jsonb, p_keys text[], p_nonzero_only boolean) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.marginflow_is_generic_document_number(value text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.marginflow_recovery_supplier_key(value text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.marginflow_try_uuid(value text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.merge_duplicate_products(p_company_id uuid, p_location_id uuid, p_keep_product_id uuid, p_merge_product_ids uuid[], p_snapshot_modules jsonb) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.merge_product_v2(p_company_id uuid, p_location_id uuid, p_keep_product_id uuid, p_merge_product_ids uuid[], p_snapshot_modules jsonb, p_expected_module_revisions jsonb) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.normalize_invoice_payload_v1(p_invoice jsonb) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.normalize_product_alias(value text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.open_support_workspace(target_company_id uuid, target_location_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.persist_invoice_document_v2(p_company_id uuid, p_location_id uuid, p_invoice jsonb) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.persist_invoice_document_v2_legacy(p_company_id uuid, p_location_id uuid, p_invoice jsonb) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.persist_invoice_document_v3(p_company_id uuid, p_location_id uuid, p_invoice jsonb, p_duplicate_action text, p_existing_invoice_id uuid, p_expected_revision bigint) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.persist_supplier_product_learning(p_company_id uuid, p_location_id uuid, p_supplier_id uuid, p_supplier_product_code text, p_normalized_supplier_product_code text, p_supplier_description text, p_normalized_supplier_description text, p_unit_of_measure text, p_normalized_unit_of_measure text, p_pack_size text, p_normalized_pack_size text, p_product_id uuid, p_allocation_mode text, p_department_id uuid, p_split_lines jsonb, p_auto_apply boolean, p_source_invoice_external_id text, p_supplier_name text, p_product_name text, p_department_name text, p_mapping_key text, p_confirmed_at timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.persist_supplier_product_learning_v2(p_company_id uuid, p_location_id uuid, p_supplier_id uuid, p_supplier_product_code text, p_normalized_supplier_product_code text, p_supplier_description text, p_normalized_supplier_description text, p_unit_of_measure text, p_normalized_unit_of_measure text, p_pack_size text, p_normalized_pack_size text, p_product_id uuid, p_allocation_mode text, p_department_id uuid, p_split_lines jsonb, p_auto_apply boolean, p_source_invoice_external_id text, p_supplier_name text, p_product_name text, p_department_name text, p_mapping_key text, p_confirmed_at timestamp with time zone, p_match_source text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.protect_marginflow_cloud_state_writes() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.provision_default_company_subscription() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.record_internal_audit_event(event_action text, event_entity_table text, event_entity_id uuid, event_company_id uuid, event_location_id uuid, event_old_record jsonb, event_new_record jsonb, event_metadata jsonb) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.recover_legacy_catalog_v1(p_company_id uuid, p_location_id uuid, p_suppliers jsonb, p_products jsonb) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.recover_legacy_invoice_v1(p_company_id uuid, p_location_id uuid, p_invoice jsonb) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.repair_invoice_financial_headers_v1(p_company_id uuid, p_location_id uuid, p_invoice_id uuid, p_expected_revision bigint, p_expected_content_fingerprint text, p_expected_subtotal numeric, p_expected_vat numeric, p_expected_discount numeric, p_expected_total numeric, p_proposed_subtotal numeric, p_proposed_vat numeric, p_proposed_discount numeric, p_proposed_total numeric, p_proof jsonb, p_repair_key text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.resolve_recovery_invoice_date_v1(p_company_id uuid, p_location_id uuid, p_legacy_invoice_id text, p_invoice_id uuid, p_expected_revision bigint, p_expected_content_fingerprint text, p_invoice_date date) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.save_cloud_state_module_v2(p_company_id uuid, p_location_id uuid, p_scope_key text, p_module_key text, p_payload jsonb, p_expected_revision bigint) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.save_customer_onboarding_departments(p_company_id uuid, p_departments jsonb) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.save_customer_onboarding_progress(p_company_id uuid, p_onboarding_step text, p_company_name text, p_country_code text, p_country_name text, p_language text, p_currency text, p_timezone text, p_default_vat numeric, p_week_starts_on text, p_target_gp numeric, p_regional_overrides jsonb) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.save_recovery_resolution_v1(p_company_id uuid, p_location_id uuid, p_resolution_type text, p_source_key text, p_decision text, p_target_id uuid, p_value jsonb, p_metadata jsonb, p_expected_revision bigint) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.set_invoice_line_signed_totals() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.set_purchasing_document_signed_totals() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.set_supplier_normalized_name() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.set_updated_at() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.validate_customer_onboarding_values(p_company_name text, p_country_code text, p_country_name text, p_language text, p_currency text, p_timezone text, p_default_vat numeric, p_week_starts_on text, p_target_gp numeric) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.verify_recovery_integrity_v1(p_company_id uuid, p_location_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.ai_runs FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.ai_settings FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.ai_usage FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.audit_log FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.companies FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.company_features FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.company_members FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.company_settings FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.credit_notes FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.departments FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.employee_availability FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.employee_rate_history FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.employees FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.features FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.holiday_adjustments FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.holiday_balances FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.holiday_bookings FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.internal_audit_log FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.internal_permissions FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.internal_role_permissions FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.internal_roles FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.internal_staff_accounts FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.internal_staff_invites FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.internal_staff_permission_overrides FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.internal_support_sessions FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.invoice_day_status_overrides FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.invoice_files FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.invoice_financial_repairs FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.invoice_line_corrections FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.invoice_line_department_splits FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.invoice_lines FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.invoices FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.labour_entries FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.labour_imports FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.labour_settings FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.legacy_invoice_archive FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.legacy_product_archive FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.locations FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.marginflow_cloud_state FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.marginflow_recovery_resolutions FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.menu_item_components FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.menu_items FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.plan_features FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.plans FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.possible_historical_credit_note_documents FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.product_merge_format_archives FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.product_merges FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.product_price_history FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.product_supplier_formats FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.product_supplier_prices FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.products FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.profiles FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.recipe_ingredients FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.recipes FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.sales_department_lines FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.sales_entries FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.schedule_weeks FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.shifts FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.stocktake_lines FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.stocktakes FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.subscriptions FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.supplier_ai_profiles FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.supplier_delivery_schedules FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.supplier_merges FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.supplier_product_mappings FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.supplier_product_split_rule_lines FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.supplier_product_split_rules FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.suppliers FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.time_off_requests FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.user_action_permissions FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.user_department_permissions FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.user_page_permissions FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.waste_entries FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.waste_photos FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.workforce_audit_log FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.workforce_employee_compensation FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.workforce_employees FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.workforce_permission_set_permissions FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.workforce_permission_sets FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.workforce_settings FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.workforce_timecards FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION marginflow.current_auth_user_id() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_invite_internal_staff(p_email text, p_full_name text, p_role_key text, p_permission_overrides jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_update_internal_staff(p_user_id uuid, p_role_key text, p_status text, p_permission_overrides jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_update_subscription(p_company_id uuid, p_status text, p_plan_slug text, p_trial_ends_at timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION public.archive_legacy_recovery_v1(p_company_id uuid, p_location_id uuid, p_products jsonb, p_invoices jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.begin_customer_onboarding(p_company_name text, p_country_code text, p_country_name text, p_language text, p_currency text, p_timezone text, p_default_vat numeric, p_week_starts_on text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_access_feature(target_company_id uuid, target_feature_key text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_access_profile(target_user_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.can_manage_company_features(target_company_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.claim_internal_staff_invite() TO authenticated;
GRANT EXECUTE ON FUNCTION public.close_support_workspace(target_session_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.company_has_no_members(target_company_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.company_has_no_members(target_company_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.company_subscription_allows_write(target_company_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.complete_customer_onboarding(p_company_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_company_with_owner(company_name text, location_name text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.current_workforce_employee_id(target_company_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.current_workforce_employee_id(target_company_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.forget_supplier_product_learning(p_company_id uuid, p_location_id uuid, p_supplier_id uuid, p_mapping_id uuid, p_normalized_supplier_product_code text, p_normalized_supplier_description text, p_normalized_unit_of_measure text, p_normalized_pack_size text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_admin_audit_log(p_company_id uuid, p_actor_id uuid, p_action text, p_from timestamp with time zone, p_to timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_admin_companies(p_search text, p_status text, p_plan text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_admin_company_detail(target_company_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_admin_overview() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_admin_plans() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_admin_staff() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_customer_onboarding_state(p_company_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_effective_company_access(target_company_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_internal_admin_context() TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_internal_permission(target_permission_key text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_workforce_permission(target_company_id uuid, target_permission_key text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.has_workforce_permission(target_company_id uuid, target_permission_key text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.invoice_business_fingerprint_v1(p_invoice jsonb) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_active_company_member(target_company_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_company_feature_beta_eligible(target_company_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_company_owner(target_company_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_customer_onboarding_owner(target_company_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_internal_staff() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_platform_owner() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_support_workspace_scope(target_company_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.marginflow_first_numeric(p_payload jsonb, p_keys text[], p_nonzero_only boolean) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.marginflow_is_generic_document_number(value text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.marginflow_recovery_supplier_key(value text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.marginflow_try_uuid(value text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.merge_duplicate_products(p_company_id uuid, p_location_id uuid, p_keep_product_id uuid, p_merge_product_ids uuid[], p_snapshot_modules jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.merge_product_v2(p_company_id uuid, p_location_id uuid, p_keep_product_id uuid, p_merge_product_ids uuid[], p_snapshot_modules jsonb, p_expected_module_revisions jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.normalize_invoice_payload_v1(p_invoice jsonb) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.normalize_product_alias(value text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.open_support_workspace(target_company_id uuid, target_location_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.persist_invoice_document_v2(p_company_id uuid, p_location_id uuid, p_invoice jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.persist_invoice_document_v3(p_company_id uuid, p_location_id uuid, p_invoice jsonb, p_duplicate_action text, p_existing_invoice_id uuid, p_expected_revision bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.persist_supplier_product_learning(p_company_id uuid, p_location_id uuid, p_supplier_id uuid, p_supplier_product_code text, p_normalized_supplier_product_code text, p_supplier_description text, p_normalized_supplier_description text, p_unit_of_measure text, p_normalized_unit_of_measure text, p_pack_size text, p_normalized_pack_size text, p_product_id uuid, p_allocation_mode text, p_department_id uuid, p_split_lines jsonb, p_auto_apply boolean, p_source_invoice_external_id text, p_supplier_name text, p_product_name text, p_department_name text, p_mapping_key text, p_confirmed_at timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION public.persist_supplier_product_learning_v2(p_company_id uuid, p_location_id uuid, p_supplier_id uuid, p_supplier_product_code text, p_normalized_supplier_product_code text, p_supplier_description text, p_normalized_supplier_description text, p_unit_of_measure text, p_normalized_unit_of_measure text, p_pack_size text, p_normalized_pack_size text, p_product_id uuid, p_allocation_mode text, p_department_id uuid, p_split_lines jsonb, p_auto_apply boolean, p_source_invoice_external_id text, p_supplier_name text, p_product_name text, p_department_name text, p_mapping_key text, p_confirmed_at timestamp with time zone, p_match_source text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.protect_marginflow_cloud_state_writes() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.provision_default_company_subscription() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.record_internal_audit_event(event_action text, event_entity_table text, event_entity_id uuid, event_company_id uuid, event_location_id uuid, event_old_record jsonb, event_new_record jsonb, event_metadata jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.recover_legacy_catalog_v1(p_company_id uuid, p_location_id uuid, p_suppliers jsonb, p_products jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.recover_legacy_invoice_v1(p_company_id uuid, p_location_id uuid, p_invoice jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.repair_invoice_financial_headers_v1(p_company_id uuid, p_location_id uuid, p_invoice_id uuid, p_expected_revision bigint, p_expected_content_fingerprint text, p_expected_subtotal numeric, p_expected_vat numeric, p_expected_discount numeric, p_expected_total numeric, p_proposed_subtotal numeric, p_proposed_vat numeric, p_proposed_discount numeric, p_proposed_total numeric, p_proof jsonb, p_repair_key text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.resolve_recovery_invoice_date_v1(p_company_id uuid, p_location_id uuid, p_legacy_invoice_id text, p_invoice_id uuid, p_expected_revision bigint, p_expected_content_fingerprint text, p_invoice_date date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_cloud_state_module_v2(p_company_id uuid, p_location_id uuid, p_scope_key text, p_module_key text, p_payload jsonb, p_expected_revision bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_customer_onboarding_departments(p_company_id uuid, p_departments jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_customer_onboarding_progress(p_company_id uuid, p_onboarding_step text, p_company_name text, p_country_code text, p_country_name text, p_language text, p_currency text, p_timezone text, p_default_vat numeric, p_week_starts_on text, p_target_gp numeric, p_regional_overrides jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_recovery_resolution_v1(p_company_id uuid, p_location_id uuid, p_resolution_type text, p_source_key text, p_decision text, p_target_id uuid, p_value jsonb, p_metadata jsonb, p_expected_revision bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_invoice_line_signed_totals() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.set_purchasing_document_signed_totals() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.set_supplier_normalized_name() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.set_updated_at() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.verify_recovery_integrity_v1(p_company_id uuid, p_location_id uuid) TO authenticated;
GRANT REFERENCES ON TABLE public.ai_runs TO anon;
GRANT TRIGGER ON TABLE public.ai_runs TO anon;
GRANT TRUNCATE ON TABLE public.ai_runs TO anon;
GRANT DELETE ON TABLE public.ai_runs TO authenticated;
GRANT INSERT ON TABLE public.ai_runs TO authenticated;
GRANT REFERENCES ON TABLE public.ai_runs TO authenticated;
GRANT SELECT ON TABLE public.ai_runs TO authenticated;
GRANT TRIGGER ON TABLE public.ai_runs TO authenticated;
GRANT TRUNCATE ON TABLE public.ai_runs TO authenticated;
GRANT UPDATE ON TABLE public.ai_runs TO authenticated;
GRANT REFERENCES ON TABLE public.ai_runs TO service_role;
GRANT TRIGGER ON TABLE public.ai_runs TO service_role;
GRANT TRUNCATE ON TABLE public.ai_runs TO service_role;
GRANT REFERENCES ON TABLE public.ai_settings TO anon;
GRANT TRIGGER ON TABLE public.ai_settings TO anon;
GRANT TRUNCATE ON TABLE public.ai_settings TO anon;
GRANT DELETE ON TABLE public.ai_settings TO authenticated;
GRANT INSERT ON TABLE public.ai_settings TO authenticated;
GRANT REFERENCES ON TABLE public.ai_settings TO authenticated;
GRANT SELECT ON TABLE public.ai_settings TO authenticated;
GRANT TRIGGER ON TABLE public.ai_settings TO authenticated;
GRANT TRUNCATE ON TABLE public.ai_settings TO authenticated;
GRANT UPDATE ON TABLE public.ai_settings TO authenticated;
GRANT REFERENCES ON TABLE public.ai_settings TO service_role;
GRANT TRIGGER ON TABLE public.ai_settings TO service_role;
GRANT TRUNCATE ON TABLE public.ai_settings TO service_role;
GRANT REFERENCES ON TABLE public.ai_usage TO anon;
GRANT TRIGGER ON TABLE public.ai_usage TO anon;
GRANT TRUNCATE ON TABLE public.ai_usage TO anon;
GRANT DELETE ON TABLE public.ai_usage TO authenticated;
GRANT INSERT ON TABLE public.ai_usage TO authenticated;
GRANT REFERENCES ON TABLE public.ai_usage TO authenticated;
GRANT SELECT ON TABLE public.ai_usage TO authenticated;
GRANT TRIGGER ON TABLE public.ai_usage TO authenticated;
GRANT TRUNCATE ON TABLE public.ai_usage TO authenticated;
GRANT UPDATE ON TABLE public.ai_usage TO authenticated;
GRANT REFERENCES ON TABLE public.ai_usage TO service_role;
GRANT TRIGGER ON TABLE public.ai_usage TO service_role;
GRANT TRUNCATE ON TABLE public.ai_usage TO service_role;
GRANT REFERENCES ON TABLE public.audit_log TO anon;
GRANT TRIGGER ON TABLE public.audit_log TO anon;
GRANT TRUNCATE ON TABLE public.audit_log TO anon;
GRANT DELETE ON TABLE public.audit_log TO authenticated;
GRANT INSERT ON TABLE public.audit_log TO authenticated;
GRANT REFERENCES ON TABLE public.audit_log TO authenticated;
GRANT SELECT ON TABLE public.audit_log TO authenticated;
GRANT TRIGGER ON TABLE public.audit_log TO authenticated;
GRANT TRUNCATE ON TABLE public.audit_log TO authenticated;
GRANT UPDATE ON TABLE public.audit_log TO authenticated;
GRANT REFERENCES ON TABLE public.audit_log TO service_role;
GRANT TRIGGER ON TABLE public.audit_log TO service_role;
GRANT TRUNCATE ON TABLE public.audit_log TO service_role;
GRANT REFERENCES ON TABLE public.companies TO anon;
GRANT TRIGGER ON TABLE public.companies TO anon;
GRANT TRUNCATE ON TABLE public.companies TO anon;
GRANT REFERENCES ON TABLE public.companies TO authenticated;
GRANT SELECT ON TABLE public.companies TO authenticated;
GRANT TRIGGER ON TABLE public.companies TO authenticated;
GRANT TRUNCATE ON TABLE public.companies TO authenticated;
GRANT REFERENCES ON TABLE public.companies TO service_role;
GRANT TRIGGER ON TABLE public.companies TO service_role;
GRANT TRUNCATE ON TABLE public.companies TO service_role;
GRANT DELETE ON TABLE public.company_features TO authenticated;
GRANT INSERT ON TABLE public.company_features TO authenticated;
GRANT SELECT ON TABLE public.company_features TO authenticated;
GRANT UPDATE ON TABLE public.company_features TO authenticated;
GRANT REFERENCES ON TABLE public.company_features TO service_role;
GRANT TRIGGER ON TABLE public.company_features TO service_role;
GRANT TRUNCATE ON TABLE public.company_features TO service_role;
GRANT REFERENCES ON TABLE public.company_members TO anon;
GRANT TRIGGER ON TABLE public.company_members TO anon;
GRANT TRUNCATE ON TABLE public.company_members TO anon;
GRANT DELETE ON TABLE public.company_members TO authenticated;
GRANT INSERT ON TABLE public.company_members TO authenticated;
GRANT REFERENCES ON TABLE public.company_members TO authenticated;
GRANT SELECT ON TABLE public.company_members TO authenticated;
GRANT TRIGGER ON TABLE public.company_members TO authenticated;
GRANT TRUNCATE ON TABLE public.company_members TO authenticated;
GRANT UPDATE ON TABLE public.company_members TO authenticated;
GRANT REFERENCES ON TABLE public.company_members TO service_role;
GRANT TRIGGER ON TABLE public.company_members TO service_role;
GRANT TRUNCATE ON TABLE public.company_members TO service_role;
GRANT REFERENCES ON TABLE public.company_settings TO anon;
GRANT TRIGGER ON TABLE public.company_settings TO anon;
GRANT TRUNCATE ON TABLE public.company_settings TO anon;
GRANT DELETE ON TABLE public.company_settings TO authenticated;
GRANT INSERT ON TABLE public.company_settings TO authenticated;
GRANT REFERENCES ON TABLE public.company_settings TO authenticated;
GRANT SELECT ON TABLE public.company_settings TO authenticated;
GRANT TRIGGER ON TABLE public.company_settings TO authenticated;
GRANT TRUNCATE ON TABLE public.company_settings TO authenticated;
GRANT UPDATE ON TABLE public.company_settings TO authenticated;
GRANT REFERENCES ON TABLE public.company_settings TO service_role;
GRANT TRIGGER ON TABLE public.company_settings TO service_role;
GRANT TRUNCATE ON TABLE public.company_settings TO service_role;
GRANT REFERENCES ON TABLE public.credit_notes TO anon;
GRANT TRIGGER ON TABLE public.credit_notes TO anon;
GRANT TRUNCATE ON TABLE public.credit_notes TO anon;
GRANT DELETE ON TABLE public.credit_notes TO authenticated;
GRANT INSERT ON TABLE public.credit_notes TO authenticated;
GRANT REFERENCES ON TABLE public.credit_notes TO authenticated;
GRANT SELECT ON TABLE public.credit_notes TO authenticated;
GRANT TRIGGER ON TABLE public.credit_notes TO authenticated;
GRANT TRUNCATE ON TABLE public.credit_notes TO authenticated;
GRANT UPDATE ON TABLE public.credit_notes TO authenticated;
GRANT REFERENCES ON TABLE public.credit_notes TO service_role;
GRANT TRIGGER ON TABLE public.credit_notes TO service_role;
GRANT TRUNCATE ON TABLE public.credit_notes TO service_role;
GRANT REFERENCES ON TABLE public.departments TO anon;
GRANT TRIGGER ON TABLE public.departments TO anon;
GRANT TRUNCATE ON TABLE public.departments TO anon;
GRANT DELETE ON TABLE public.departments TO authenticated;
GRANT INSERT ON TABLE public.departments TO authenticated;
GRANT REFERENCES ON TABLE public.departments TO authenticated;
GRANT SELECT ON TABLE public.departments TO authenticated;
GRANT TRIGGER ON TABLE public.departments TO authenticated;
GRANT TRUNCATE ON TABLE public.departments TO authenticated;
GRANT UPDATE ON TABLE public.departments TO authenticated;
GRANT REFERENCES ON TABLE public.departments TO service_role;
GRANT TRIGGER ON TABLE public.departments TO service_role;
GRANT TRUNCATE ON TABLE public.departments TO service_role;
GRANT REFERENCES ON TABLE public.employee_availability TO anon;
GRANT TRIGGER ON TABLE public.employee_availability TO anon;
GRANT TRUNCATE ON TABLE public.employee_availability TO anon;
GRANT DELETE ON TABLE public.employee_availability TO authenticated;
GRANT INSERT ON TABLE public.employee_availability TO authenticated;
GRANT REFERENCES ON TABLE public.employee_availability TO authenticated;
GRANT SELECT ON TABLE public.employee_availability TO authenticated;
GRANT TRIGGER ON TABLE public.employee_availability TO authenticated;
GRANT TRUNCATE ON TABLE public.employee_availability TO authenticated;
GRANT UPDATE ON TABLE public.employee_availability TO authenticated;
GRANT REFERENCES ON TABLE public.employee_availability TO service_role;
GRANT TRIGGER ON TABLE public.employee_availability TO service_role;
GRANT TRUNCATE ON TABLE public.employee_availability TO service_role;
GRANT REFERENCES ON TABLE public.employee_rate_history TO anon;
GRANT TRIGGER ON TABLE public.employee_rate_history TO anon;
GRANT TRUNCATE ON TABLE public.employee_rate_history TO anon;
GRANT DELETE ON TABLE public.employee_rate_history TO authenticated;
GRANT INSERT ON TABLE public.employee_rate_history TO authenticated;
GRANT REFERENCES ON TABLE public.employee_rate_history TO authenticated;
GRANT SELECT ON TABLE public.employee_rate_history TO authenticated;
GRANT TRIGGER ON TABLE public.employee_rate_history TO authenticated;
GRANT TRUNCATE ON TABLE public.employee_rate_history TO authenticated;
GRANT UPDATE ON TABLE public.employee_rate_history TO authenticated;
GRANT REFERENCES ON TABLE public.employee_rate_history TO service_role;
GRANT TRIGGER ON TABLE public.employee_rate_history TO service_role;
GRANT TRUNCATE ON TABLE public.employee_rate_history TO service_role;
GRANT REFERENCES ON TABLE public.employees TO anon;
GRANT TRIGGER ON TABLE public.employees TO anon;
GRANT TRUNCATE ON TABLE public.employees TO anon;
GRANT DELETE ON TABLE public.employees TO authenticated;
GRANT INSERT ON TABLE public.employees TO authenticated;
GRANT REFERENCES ON TABLE public.employees TO authenticated;
GRANT SELECT ON TABLE public.employees TO authenticated;
GRANT TRIGGER ON TABLE public.employees TO authenticated;
GRANT TRUNCATE ON TABLE public.employees TO authenticated;
GRANT UPDATE ON TABLE public.employees TO authenticated;
GRANT REFERENCES ON TABLE public.employees TO service_role;
GRANT TRIGGER ON TABLE public.employees TO service_role;
GRANT TRUNCATE ON TABLE public.employees TO service_role;
GRANT DELETE ON TABLE public.features TO authenticated;
GRANT INSERT ON TABLE public.features TO authenticated;
GRANT REFERENCES ON TABLE public.features TO authenticated;
GRANT SELECT ON TABLE public.features TO authenticated;
GRANT TRIGGER ON TABLE public.features TO authenticated;
GRANT TRUNCATE ON TABLE public.features TO authenticated;
GRANT UPDATE ON TABLE public.features TO authenticated;
GRANT REFERENCES ON TABLE public.features TO service_role;
GRANT TRIGGER ON TABLE public.features TO service_role;
GRANT TRUNCATE ON TABLE public.features TO service_role;
GRANT REFERENCES ON TABLE public.holiday_adjustments TO anon;
GRANT TRIGGER ON TABLE public.holiday_adjustments TO anon;
GRANT TRUNCATE ON TABLE public.holiday_adjustments TO anon;
GRANT DELETE ON TABLE public.holiday_adjustments TO authenticated;
GRANT INSERT ON TABLE public.holiday_adjustments TO authenticated;
GRANT REFERENCES ON TABLE public.holiday_adjustments TO authenticated;
GRANT SELECT ON TABLE public.holiday_adjustments TO authenticated;
GRANT TRIGGER ON TABLE public.holiday_adjustments TO authenticated;
GRANT TRUNCATE ON TABLE public.holiday_adjustments TO authenticated;
GRANT UPDATE ON TABLE public.holiday_adjustments TO authenticated;
GRANT REFERENCES ON TABLE public.holiday_adjustments TO service_role;
GRANT TRIGGER ON TABLE public.holiday_adjustments TO service_role;
GRANT TRUNCATE ON TABLE public.holiday_adjustments TO service_role;
GRANT REFERENCES ON TABLE public.holiday_balances TO anon;
GRANT TRIGGER ON TABLE public.holiday_balances TO anon;
GRANT TRUNCATE ON TABLE public.holiday_balances TO anon;
GRANT DELETE ON TABLE public.holiday_balances TO authenticated;
GRANT INSERT ON TABLE public.holiday_balances TO authenticated;
GRANT REFERENCES ON TABLE public.holiday_balances TO authenticated;
GRANT SELECT ON TABLE public.holiday_balances TO authenticated;
GRANT TRIGGER ON TABLE public.holiday_balances TO authenticated;
GRANT TRUNCATE ON TABLE public.holiday_balances TO authenticated;
GRANT UPDATE ON TABLE public.holiday_balances TO authenticated;
GRANT REFERENCES ON TABLE public.holiday_balances TO service_role;
GRANT TRIGGER ON TABLE public.holiday_balances TO service_role;
GRANT TRUNCATE ON TABLE public.holiday_balances TO service_role;
GRANT REFERENCES ON TABLE public.holiday_bookings TO anon;
GRANT TRIGGER ON TABLE public.holiday_bookings TO anon;
GRANT TRUNCATE ON TABLE public.holiday_bookings TO anon;
GRANT DELETE ON TABLE public.holiday_bookings TO authenticated;
GRANT INSERT ON TABLE public.holiday_bookings TO authenticated;
GRANT REFERENCES ON TABLE public.holiday_bookings TO authenticated;
GRANT SELECT ON TABLE public.holiday_bookings TO authenticated;
GRANT TRIGGER ON TABLE public.holiday_bookings TO authenticated;
GRANT TRUNCATE ON TABLE public.holiday_bookings TO authenticated;
GRANT UPDATE ON TABLE public.holiday_bookings TO authenticated;
GRANT REFERENCES ON TABLE public.holiday_bookings TO service_role;
GRANT TRIGGER ON TABLE public.holiday_bookings TO service_role;
GRANT TRUNCATE ON TABLE public.holiday_bookings TO service_role;
GRANT SELECT ON TABLE public.internal_audit_log TO authenticated;
GRANT REFERENCES ON TABLE public.internal_audit_log TO service_role;
GRANT TRIGGER ON TABLE public.internal_audit_log TO service_role;
GRANT TRUNCATE ON TABLE public.internal_audit_log TO service_role;
GRANT DELETE ON TABLE public.internal_permissions TO authenticated;
GRANT INSERT ON TABLE public.internal_permissions TO authenticated;
GRANT REFERENCES ON TABLE public.internal_permissions TO authenticated;
GRANT SELECT ON TABLE public.internal_permissions TO authenticated;
GRANT TRIGGER ON TABLE public.internal_permissions TO authenticated;
GRANT TRUNCATE ON TABLE public.internal_permissions TO authenticated;
GRANT UPDATE ON TABLE public.internal_permissions TO authenticated;
GRANT REFERENCES ON TABLE public.internal_permissions TO service_role;
GRANT TRIGGER ON TABLE public.internal_permissions TO service_role;
GRANT TRUNCATE ON TABLE public.internal_permissions TO service_role;
GRANT DELETE ON TABLE public.internal_role_permissions TO authenticated;
GRANT INSERT ON TABLE public.internal_role_permissions TO authenticated;
GRANT REFERENCES ON TABLE public.internal_role_permissions TO authenticated;
GRANT SELECT ON TABLE public.internal_role_permissions TO authenticated;
GRANT TRIGGER ON TABLE public.internal_role_permissions TO authenticated;
GRANT TRUNCATE ON TABLE public.internal_role_permissions TO authenticated;
GRANT UPDATE ON TABLE public.internal_role_permissions TO authenticated;
GRANT REFERENCES ON TABLE public.internal_role_permissions TO service_role;
GRANT TRIGGER ON TABLE public.internal_role_permissions TO service_role;
GRANT TRUNCATE ON TABLE public.internal_role_permissions TO service_role;
GRANT DELETE ON TABLE public.internal_roles TO authenticated;
GRANT INSERT ON TABLE public.internal_roles TO authenticated;
GRANT REFERENCES ON TABLE public.internal_roles TO authenticated;
GRANT SELECT ON TABLE public.internal_roles TO authenticated;
GRANT TRIGGER ON TABLE public.internal_roles TO authenticated;
GRANT TRUNCATE ON TABLE public.internal_roles TO authenticated;
GRANT UPDATE ON TABLE public.internal_roles TO authenticated;
GRANT REFERENCES ON TABLE public.internal_roles TO service_role;
GRANT TRIGGER ON TABLE public.internal_roles TO service_role;
GRANT TRUNCATE ON TABLE public.internal_roles TO service_role;
GRANT DELETE ON TABLE public.internal_staff_accounts TO authenticated;
GRANT INSERT ON TABLE public.internal_staff_accounts TO authenticated;
GRANT REFERENCES ON TABLE public.internal_staff_accounts TO authenticated;
GRANT SELECT ON TABLE public.internal_staff_accounts TO authenticated;
GRANT TRIGGER ON TABLE public.internal_staff_accounts TO authenticated;
GRANT TRUNCATE ON TABLE public.internal_staff_accounts TO authenticated;
GRANT UPDATE ON TABLE public.internal_staff_accounts TO authenticated;
GRANT REFERENCES ON TABLE public.internal_staff_accounts TO service_role;
GRANT TRIGGER ON TABLE public.internal_staff_accounts TO service_role;
GRANT TRUNCATE ON TABLE public.internal_staff_accounts TO service_role;
GRANT REFERENCES ON TABLE public.internal_staff_invites TO service_role;
GRANT TRIGGER ON TABLE public.internal_staff_invites TO service_role;
GRANT TRUNCATE ON TABLE public.internal_staff_invites TO service_role;
GRANT DELETE ON TABLE public.internal_staff_permission_overrides TO authenticated;
GRANT INSERT ON TABLE public.internal_staff_permission_overrides TO authenticated;
GRANT REFERENCES ON TABLE public.internal_staff_permission_overrides TO authenticated;
GRANT SELECT ON TABLE public.internal_staff_permission_overrides TO authenticated;
GRANT TRIGGER ON TABLE public.internal_staff_permission_overrides TO authenticated;
GRANT TRUNCATE ON TABLE public.internal_staff_permission_overrides TO authenticated;
GRANT UPDATE ON TABLE public.internal_staff_permission_overrides TO authenticated;
GRANT REFERENCES ON TABLE public.internal_staff_permission_overrides TO service_role;
GRANT TRIGGER ON TABLE public.internal_staff_permission_overrides TO service_role;
GRANT TRUNCATE ON TABLE public.internal_staff_permission_overrides TO service_role;
GRANT REFERENCES ON TABLE public.internal_support_sessions TO service_role;
GRANT TRIGGER ON TABLE public.internal_support_sessions TO service_role;
GRANT TRUNCATE ON TABLE public.internal_support_sessions TO service_role;
GRANT REFERENCES ON TABLE public.invoice_day_status_overrides TO anon;
GRANT TRIGGER ON TABLE public.invoice_day_status_overrides TO anon;
GRANT TRUNCATE ON TABLE public.invoice_day_status_overrides TO anon;
GRANT REFERENCES ON TABLE public.invoice_day_status_overrides TO authenticated;
GRANT TRIGGER ON TABLE public.invoice_day_status_overrides TO authenticated;
GRANT TRUNCATE ON TABLE public.invoice_day_status_overrides TO authenticated;
GRANT REFERENCES ON TABLE public.invoice_day_status_overrides TO service_role;
GRANT TRIGGER ON TABLE public.invoice_day_status_overrides TO service_role;
GRANT TRUNCATE ON TABLE public.invoice_day_status_overrides TO service_role;
GRANT REFERENCES ON TABLE public.invoice_files TO anon;
GRANT TRIGGER ON TABLE public.invoice_files TO anon;
GRANT TRUNCATE ON TABLE public.invoice_files TO anon;
GRANT DELETE ON TABLE public.invoice_files TO authenticated;
GRANT INSERT ON TABLE public.invoice_files TO authenticated;
GRANT REFERENCES ON TABLE public.invoice_files TO authenticated;
GRANT SELECT ON TABLE public.invoice_files TO authenticated;
GRANT TRIGGER ON TABLE public.invoice_files TO authenticated;
GRANT TRUNCATE ON TABLE public.invoice_files TO authenticated;
GRANT UPDATE ON TABLE public.invoice_files TO authenticated;
GRANT REFERENCES ON TABLE public.invoice_files TO service_role;
GRANT TRIGGER ON TABLE public.invoice_files TO service_role;
GRANT TRUNCATE ON TABLE public.invoice_files TO service_role;
GRANT REFERENCES ON TABLE public.invoice_financial_repairs TO anon;
GRANT TRIGGER ON TABLE public.invoice_financial_repairs TO anon;
GRANT TRUNCATE ON TABLE public.invoice_financial_repairs TO anon;
GRANT REFERENCES ON TABLE public.invoice_financial_repairs TO authenticated;
GRANT TRIGGER ON TABLE public.invoice_financial_repairs TO authenticated;
GRANT TRUNCATE ON TABLE public.invoice_financial_repairs TO authenticated;
GRANT REFERENCES ON TABLE public.invoice_financial_repairs TO service_role;
GRANT TRIGGER ON TABLE public.invoice_financial_repairs TO service_role;
GRANT TRUNCATE ON TABLE public.invoice_financial_repairs TO service_role;
GRANT REFERENCES ON TABLE public.invoice_line_corrections TO anon;
GRANT TRIGGER ON TABLE public.invoice_line_corrections TO anon;
GRANT TRUNCATE ON TABLE public.invoice_line_corrections TO anon;
GRANT REFERENCES ON TABLE public.invoice_line_corrections TO authenticated;
GRANT SELECT ON TABLE public.invoice_line_corrections TO authenticated;
GRANT TRIGGER ON TABLE public.invoice_line_corrections TO authenticated;
GRANT TRUNCATE ON TABLE public.invoice_line_corrections TO authenticated;
GRANT REFERENCES ON TABLE public.invoice_line_corrections TO service_role;
GRANT TRIGGER ON TABLE public.invoice_line_corrections TO service_role;
GRANT TRUNCATE ON TABLE public.invoice_line_corrections TO service_role;
GRANT REFERENCES ON TABLE public.invoice_line_department_splits TO anon;
GRANT TRIGGER ON TABLE public.invoice_line_department_splits TO anon;
GRANT TRUNCATE ON TABLE public.invoice_line_department_splits TO anon;
GRANT DELETE ON TABLE public.invoice_line_department_splits TO authenticated;
GRANT INSERT ON TABLE public.invoice_line_department_splits TO authenticated;
GRANT REFERENCES ON TABLE public.invoice_line_department_splits TO authenticated;
GRANT SELECT ON TABLE public.invoice_line_department_splits TO authenticated;
GRANT TRIGGER ON TABLE public.invoice_line_department_splits TO authenticated;
GRANT TRUNCATE ON TABLE public.invoice_line_department_splits TO authenticated;
GRANT UPDATE ON TABLE public.invoice_line_department_splits TO authenticated;
GRANT REFERENCES ON TABLE public.invoice_line_department_splits TO service_role;
GRANT TRIGGER ON TABLE public.invoice_line_department_splits TO service_role;
GRANT TRUNCATE ON TABLE public.invoice_line_department_splits TO service_role;
GRANT REFERENCES ON TABLE public.invoice_lines TO anon;
GRANT TRIGGER ON TABLE public.invoice_lines TO anon;
GRANT TRUNCATE ON TABLE public.invoice_lines TO anon;
GRANT DELETE ON TABLE public.invoice_lines TO authenticated;
GRANT INSERT ON TABLE public.invoice_lines TO authenticated;
GRANT REFERENCES ON TABLE public.invoice_lines TO authenticated;
GRANT SELECT ON TABLE public.invoice_lines TO authenticated;
GRANT TRIGGER ON TABLE public.invoice_lines TO authenticated;
GRANT TRUNCATE ON TABLE public.invoice_lines TO authenticated;
GRANT UPDATE ON TABLE public.invoice_lines TO authenticated;
GRANT REFERENCES ON TABLE public.invoice_lines TO service_role;
GRANT TRIGGER ON TABLE public.invoice_lines TO service_role;
GRANT TRUNCATE ON TABLE public.invoice_lines TO service_role;
GRANT REFERENCES ON TABLE public.invoices TO anon;
GRANT TRIGGER ON TABLE public.invoices TO anon;
GRANT TRUNCATE ON TABLE public.invoices TO anon;
GRANT DELETE ON TABLE public.invoices TO authenticated;
GRANT INSERT ON TABLE public.invoices TO authenticated;
GRANT REFERENCES ON TABLE public.invoices TO authenticated;
GRANT SELECT ON TABLE public.invoices TO authenticated;
GRANT TRIGGER ON TABLE public.invoices TO authenticated;
GRANT TRUNCATE ON TABLE public.invoices TO authenticated;
GRANT UPDATE ON TABLE public.invoices TO authenticated;
GRANT REFERENCES ON TABLE public.invoices TO service_role;
GRANT TRIGGER ON TABLE public.invoices TO service_role;
GRANT TRUNCATE ON TABLE public.invoices TO service_role;
GRANT REFERENCES ON TABLE public.labour_entries TO anon;
GRANT TRIGGER ON TABLE public.labour_entries TO anon;
GRANT TRUNCATE ON TABLE public.labour_entries TO anon;
GRANT DELETE ON TABLE public.labour_entries TO authenticated;
GRANT INSERT ON TABLE public.labour_entries TO authenticated;
GRANT REFERENCES ON TABLE public.labour_entries TO authenticated;
GRANT SELECT ON TABLE public.labour_entries TO authenticated;
GRANT TRIGGER ON TABLE public.labour_entries TO authenticated;
GRANT TRUNCATE ON TABLE public.labour_entries TO authenticated;
GRANT UPDATE ON TABLE public.labour_entries TO authenticated;
GRANT REFERENCES ON TABLE public.labour_entries TO service_role;
GRANT TRIGGER ON TABLE public.labour_entries TO service_role;
GRANT TRUNCATE ON TABLE public.labour_entries TO service_role;
GRANT REFERENCES ON TABLE public.labour_imports TO anon;
GRANT TRIGGER ON TABLE public.labour_imports TO anon;
GRANT TRUNCATE ON TABLE public.labour_imports TO anon;
GRANT DELETE ON TABLE public.labour_imports TO authenticated;
GRANT INSERT ON TABLE public.labour_imports TO authenticated;
GRANT REFERENCES ON TABLE public.labour_imports TO authenticated;
GRANT SELECT ON TABLE public.labour_imports TO authenticated;
GRANT TRIGGER ON TABLE public.labour_imports TO authenticated;
GRANT TRUNCATE ON TABLE public.labour_imports TO authenticated;
GRANT UPDATE ON TABLE public.labour_imports TO authenticated;
GRANT REFERENCES ON TABLE public.labour_imports TO service_role;
GRANT TRIGGER ON TABLE public.labour_imports TO service_role;
GRANT TRUNCATE ON TABLE public.labour_imports TO service_role;
GRANT REFERENCES ON TABLE public.labour_settings TO anon;
GRANT TRIGGER ON TABLE public.labour_settings TO anon;
GRANT TRUNCATE ON TABLE public.labour_settings TO anon;
GRANT DELETE ON TABLE public.labour_settings TO authenticated;
GRANT INSERT ON TABLE public.labour_settings TO authenticated;
GRANT REFERENCES ON TABLE public.labour_settings TO authenticated;
GRANT SELECT ON TABLE public.labour_settings TO authenticated;
GRANT TRIGGER ON TABLE public.labour_settings TO authenticated;
GRANT TRUNCATE ON TABLE public.labour_settings TO authenticated;
GRANT UPDATE ON TABLE public.labour_settings TO authenticated;
GRANT REFERENCES ON TABLE public.labour_settings TO service_role;
GRANT TRIGGER ON TABLE public.labour_settings TO service_role;
GRANT TRUNCATE ON TABLE public.labour_settings TO service_role;
GRANT SELECT ON TABLE public.legacy_invoice_archive TO authenticated;
GRANT REFERENCES ON TABLE public.legacy_invoice_archive TO service_role;
GRANT TRIGGER ON TABLE public.legacy_invoice_archive TO service_role;
GRANT TRUNCATE ON TABLE public.legacy_invoice_archive TO service_role;
GRANT SELECT ON TABLE public.legacy_product_archive TO authenticated;
GRANT REFERENCES ON TABLE public.legacy_product_archive TO service_role;
GRANT TRIGGER ON TABLE public.legacy_product_archive TO service_role;
GRANT TRUNCATE ON TABLE public.legacy_product_archive TO service_role;
GRANT REFERENCES ON TABLE public.locations TO anon;
GRANT TRIGGER ON TABLE public.locations TO anon;
GRANT TRUNCATE ON TABLE public.locations TO anon;
GRANT DELETE ON TABLE public.locations TO authenticated;
GRANT INSERT ON TABLE public.locations TO authenticated;
GRANT REFERENCES ON TABLE public.locations TO authenticated;
GRANT SELECT ON TABLE public.locations TO authenticated;
GRANT TRIGGER ON TABLE public.locations TO authenticated;
GRANT TRUNCATE ON TABLE public.locations TO authenticated;
GRANT UPDATE ON TABLE public.locations TO authenticated;
GRANT REFERENCES ON TABLE public.locations TO service_role;
GRANT TRIGGER ON TABLE public.locations TO service_role;
GRANT TRUNCATE ON TABLE public.locations TO service_role;
GRANT REFERENCES ON TABLE public.marginflow_cloud_state TO anon;
GRANT TRIGGER ON TABLE public.marginflow_cloud_state TO anon;
GRANT TRUNCATE ON TABLE public.marginflow_cloud_state TO anon;
GRANT REFERENCES ON TABLE public.marginflow_cloud_state TO authenticated;
GRANT TRIGGER ON TABLE public.marginflow_cloud_state TO authenticated;
GRANT TRUNCATE ON TABLE public.marginflow_cloud_state TO authenticated;
GRANT REFERENCES ON TABLE public.marginflow_cloud_state TO service_role;
GRANT TRIGGER ON TABLE public.marginflow_cloud_state TO service_role;
GRANT TRUNCATE ON TABLE public.marginflow_cloud_state TO service_role;
GRANT REFERENCES ON TABLE public.marginflow_recovery_resolutions TO anon;
GRANT TRIGGER ON TABLE public.marginflow_recovery_resolutions TO anon;
GRANT TRUNCATE ON TABLE public.marginflow_recovery_resolutions TO anon;
GRANT REFERENCES ON TABLE public.marginflow_recovery_resolutions TO authenticated;
GRANT SELECT ON TABLE public.marginflow_recovery_resolutions TO authenticated;
GRANT TRIGGER ON TABLE public.marginflow_recovery_resolutions TO authenticated;
GRANT TRUNCATE ON TABLE public.marginflow_recovery_resolutions TO authenticated;
GRANT REFERENCES ON TABLE public.marginflow_recovery_resolutions TO service_role;
GRANT TRIGGER ON TABLE public.marginflow_recovery_resolutions TO service_role;
GRANT TRUNCATE ON TABLE public.marginflow_recovery_resolutions TO service_role;
GRANT REFERENCES ON TABLE public.menu_item_components TO anon;
GRANT TRIGGER ON TABLE public.menu_item_components TO anon;
GRANT TRUNCATE ON TABLE public.menu_item_components TO anon;
GRANT DELETE ON TABLE public.menu_item_components TO authenticated;
GRANT INSERT ON TABLE public.menu_item_components TO authenticated;
GRANT REFERENCES ON TABLE public.menu_item_components TO authenticated;
GRANT SELECT ON TABLE public.menu_item_components TO authenticated;
GRANT TRIGGER ON TABLE public.menu_item_components TO authenticated;
GRANT TRUNCATE ON TABLE public.menu_item_components TO authenticated;
GRANT UPDATE ON TABLE public.menu_item_components TO authenticated;
GRANT REFERENCES ON TABLE public.menu_item_components TO service_role;
GRANT TRIGGER ON TABLE public.menu_item_components TO service_role;
GRANT TRUNCATE ON TABLE public.menu_item_components TO service_role;
GRANT REFERENCES ON TABLE public.menu_items TO anon;
GRANT TRIGGER ON TABLE public.menu_items TO anon;
GRANT TRUNCATE ON TABLE public.menu_items TO anon;
GRANT DELETE ON TABLE public.menu_items TO authenticated;
GRANT INSERT ON TABLE public.menu_items TO authenticated;
GRANT REFERENCES ON TABLE public.menu_items TO authenticated;
GRANT SELECT ON TABLE public.menu_items TO authenticated;
GRANT TRIGGER ON TABLE public.menu_items TO authenticated;
GRANT TRUNCATE ON TABLE public.menu_items TO authenticated;
GRANT UPDATE ON TABLE public.menu_items TO authenticated;
GRANT REFERENCES ON TABLE public.menu_items TO service_role;
GRANT TRIGGER ON TABLE public.menu_items TO service_role;
GRANT TRUNCATE ON TABLE public.menu_items TO service_role;
GRANT DELETE ON TABLE public.plan_features TO authenticated;
GRANT INSERT ON TABLE public.plan_features TO authenticated;
GRANT REFERENCES ON TABLE public.plan_features TO authenticated;
GRANT SELECT ON TABLE public.plan_features TO authenticated;
GRANT TRIGGER ON TABLE public.plan_features TO authenticated;
GRANT TRUNCATE ON TABLE public.plan_features TO authenticated;
GRANT UPDATE ON TABLE public.plan_features TO authenticated;
GRANT REFERENCES ON TABLE public.plan_features TO service_role;
GRANT TRIGGER ON TABLE public.plan_features TO service_role;
GRANT TRUNCATE ON TABLE public.plan_features TO service_role;
GRANT REFERENCES ON TABLE public.plans TO anon;
GRANT SELECT ON TABLE public.plans TO anon;
GRANT TRIGGER ON TABLE public.plans TO anon;
GRANT TRUNCATE ON TABLE public.plans TO anon;
GRANT DELETE ON TABLE public.plans TO authenticated;
GRANT INSERT ON TABLE public.plans TO authenticated;
GRANT REFERENCES ON TABLE public.plans TO authenticated;
GRANT SELECT ON TABLE public.plans TO authenticated;
GRANT TRIGGER ON TABLE public.plans TO authenticated;
GRANT TRUNCATE ON TABLE public.plans TO authenticated;
GRANT UPDATE ON TABLE public.plans TO authenticated;
GRANT REFERENCES ON TABLE public.plans TO service_role;
GRANT TRIGGER ON TABLE public.plans TO service_role;
GRANT TRUNCATE ON TABLE public.plans TO service_role;
GRANT REFERENCES ON TABLE public.possible_historical_credit_note_documents TO anon;
GRANT TRIGGER ON TABLE public.possible_historical_credit_note_documents TO anon;
GRANT TRUNCATE ON TABLE public.possible_historical_credit_note_documents TO anon;
GRANT REFERENCES ON TABLE public.possible_historical_credit_note_documents TO authenticated;
GRANT TRIGGER ON TABLE public.possible_historical_credit_note_documents TO authenticated;
GRANT TRUNCATE ON TABLE public.possible_historical_credit_note_documents TO authenticated;
GRANT REFERENCES ON TABLE public.possible_historical_credit_note_documents TO service_role;
GRANT TRIGGER ON TABLE public.possible_historical_credit_note_documents TO service_role;
GRANT TRUNCATE ON TABLE public.possible_historical_credit_note_documents TO service_role;
GRANT REFERENCES ON TABLE public.product_merge_format_archives TO anon;
GRANT TRIGGER ON TABLE public.product_merge_format_archives TO anon;
GRANT TRUNCATE ON TABLE public.product_merge_format_archives TO anon;
GRANT REFERENCES ON TABLE public.product_merge_format_archives TO authenticated;
GRANT TRIGGER ON TABLE public.product_merge_format_archives TO authenticated;
GRANT TRUNCATE ON TABLE public.product_merge_format_archives TO authenticated;
GRANT REFERENCES ON TABLE public.product_merge_format_archives TO service_role;
GRANT TRIGGER ON TABLE public.product_merge_format_archives TO service_role;
GRANT TRUNCATE ON TABLE public.product_merge_format_archives TO service_role;
GRANT REFERENCES ON TABLE public.product_merges TO anon;
GRANT TRIGGER ON TABLE public.product_merges TO anon;
GRANT TRUNCATE ON TABLE public.product_merges TO anon;
GRANT REFERENCES ON TABLE public.product_merges TO authenticated;
GRANT TRIGGER ON TABLE public.product_merges TO authenticated;
GRANT TRUNCATE ON TABLE public.product_merges TO authenticated;
GRANT REFERENCES ON TABLE public.product_merges TO service_role;
GRANT TRIGGER ON TABLE public.product_merges TO service_role;
GRANT TRUNCATE ON TABLE public.product_merges TO service_role;
GRANT REFERENCES ON TABLE public.product_price_history TO anon;
GRANT TRIGGER ON TABLE public.product_price_history TO anon;
GRANT TRUNCATE ON TABLE public.product_price_history TO anon;
GRANT DELETE ON TABLE public.product_price_history TO authenticated;
GRANT INSERT ON TABLE public.product_price_history TO authenticated;
GRANT REFERENCES ON TABLE public.product_price_history TO authenticated;
GRANT SELECT ON TABLE public.product_price_history TO authenticated;
GRANT TRIGGER ON TABLE public.product_price_history TO authenticated;
GRANT TRUNCATE ON TABLE public.product_price_history TO authenticated;
GRANT UPDATE ON TABLE public.product_price_history TO authenticated;
GRANT REFERENCES ON TABLE public.product_price_history TO service_role;
GRANT TRIGGER ON TABLE public.product_price_history TO service_role;
GRANT TRUNCATE ON TABLE public.product_price_history TO service_role;
GRANT REFERENCES ON TABLE public.product_supplier_formats TO anon;
GRANT TRIGGER ON TABLE public.product_supplier_formats TO anon;
GRANT TRUNCATE ON TABLE public.product_supplier_formats TO anon;
GRANT REFERENCES ON TABLE public.product_supplier_formats TO authenticated;
GRANT TRIGGER ON TABLE public.product_supplier_formats TO authenticated;
GRANT TRUNCATE ON TABLE public.product_supplier_formats TO authenticated;
GRANT REFERENCES ON TABLE public.product_supplier_formats TO service_role;
GRANT TRIGGER ON TABLE public.product_supplier_formats TO service_role;
GRANT TRUNCATE ON TABLE public.product_supplier_formats TO service_role;
GRANT REFERENCES ON TABLE public.product_supplier_prices TO anon;
GRANT TRIGGER ON TABLE public.product_supplier_prices TO anon;
GRANT TRUNCATE ON TABLE public.product_supplier_prices TO anon;
GRANT DELETE ON TABLE public.product_supplier_prices TO authenticated;
GRANT INSERT ON TABLE public.product_supplier_prices TO authenticated;
GRANT REFERENCES ON TABLE public.product_supplier_prices TO authenticated;
GRANT SELECT ON TABLE public.product_supplier_prices TO authenticated;
GRANT TRIGGER ON TABLE public.product_supplier_prices TO authenticated;
GRANT TRUNCATE ON TABLE public.product_supplier_prices TO authenticated;
GRANT UPDATE ON TABLE public.product_supplier_prices TO authenticated;
GRANT REFERENCES ON TABLE public.product_supplier_prices TO service_role;
GRANT TRIGGER ON TABLE public.product_supplier_prices TO service_role;
GRANT TRUNCATE ON TABLE public.product_supplier_prices TO service_role;
GRANT REFERENCES ON TABLE public.products TO anon;
GRANT TRIGGER ON TABLE public.products TO anon;
GRANT TRUNCATE ON TABLE public.products TO anon;
GRANT DELETE ON TABLE public.products TO authenticated;
GRANT INSERT ON TABLE public.products TO authenticated;
GRANT REFERENCES ON TABLE public.products TO authenticated;
GRANT SELECT ON TABLE public.products TO authenticated;
GRANT TRIGGER ON TABLE public.products TO authenticated;
GRANT TRUNCATE ON TABLE public.products TO authenticated;
GRANT UPDATE ON TABLE public.products TO authenticated;
GRANT REFERENCES ON TABLE public.products TO service_role;
GRANT TRIGGER ON TABLE public.products TO service_role;
GRANT TRUNCATE ON TABLE public.products TO service_role;
GRANT REFERENCES ON TABLE public.profiles TO anon;
GRANT TRIGGER ON TABLE public.profiles TO anon;
GRANT TRUNCATE ON TABLE public.profiles TO anon;
GRANT DELETE ON TABLE public.profiles TO authenticated;
GRANT INSERT ON TABLE public.profiles TO authenticated;
GRANT REFERENCES ON TABLE public.profiles TO authenticated;
GRANT SELECT ON TABLE public.profiles TO authenticated;
GRANT TRIGGER ON TABLE public.profiles TO authenticated;
GRANT TRUNCATE ON TABLE public.profiles TO authenticated;
GRANT UPDATE ON TABLE public.profiles TO authenticated;
GRANT REFERENCES ON TABLE public.profiles TO service_role;
GRANT TRIGGER ON TABLE public.profiles TO service_role;
GRANT TRUNCATE ON TABLE public.profiles TO service_role;
GRANT REFERENCES ON TABLE public.recipe_ingredients TO anon;
GRANT TRIGGER ON TABLE public.recipe_ingredients TO anon;
GRANT TRUNCATE ON TABLE public.recipe_ingredients TO anon;
GRANT DELETE ON TABLE public.recipe_ingredients TO authenticated;
GRANT INSERT ON TABLE public.recipe_ingredients TO authenticated;
GRANT REFERENCES ON TABLE public.recipe_ingredients TO authenticated;
GRANT SELECT ON TABLE public.recipe_ingredients TO authenticated;
GRANT TRIGGER ON TABLE public.recipe_ingredients TO authenticated;
GRANT TRUNCATE ON TABLE public.recipe_ingredients TO authenticated;
GRANT UPDATE ON TABLE public.recipe_ingredients TO authenticated;
GRANT REFERENCES ON TABLE public.recipe_ingredients TO service_role;
GRANT TRIGGER ON TABLE public.recipe_ingredients TO service_role;
GRANT TRUNCATE ON TABLE public.recipe_ingredients TO service_role;
GRANT REFERENCES ON TABLE public.recipes TO anon;
GRANT TRIGGER ON TABLE public.recipes TO anon;
GRANT TRUNCATE ON TABLE public.recipes TO anon;
GRANT DELETE ON TABLE public.recipes TO authenticated;
GRANT INSERT ON TABLE public.recipes TO authenticated;
GRANT REFERENCES ON TABLE public.recipes TO authenticated;
GRANT SELECT ON TABLE public.recipes TO authenticated;
GRANT TRIGGER ON TABLE public.recipes TO authenticated;
GRANT TRUNCATE ON TABLE public.recipes TO authenticated;
GRANT UPDATE ON TABLE public.recipes TO authenticated;
GRANT REFERENCES ON TABLE public.recipes TO service_role;
GRANT TRIGGER ON TABLE public.recipes TO service_role;
GRANT TRUNCATE ON TABLE public.recipes TO service_role;
GRANT REFERENCES ON TABLE public.sales_department_lines TO anon;
GRANT TRIGGER ON TABLE public.sales_department_lines TO anon;
GRANT TRUNCATE ON TABLE public.sales_department_lines TO anon;
GRANT DELETE ON TABLE public.sales_department_lines TO authenticated;
GRANT INSERT ON TABLE public.sales_department_lines TO authenticated;
GRANT REFERENCES ON TABLE public.sales_department_lines TO authenticated;
GRANT SELECT ON TABLE public.sales_department_lines TO authenticated;
GRANT TRIGGER ON TABLE public.sales_department_lines TO authenticated;
GRANT TRUNCATE ON TABLE public.sales_department_lines TO authenticated;
GRANT UPDATE ON TABLE public.sales_department_lines TO authenticated;
GRANT REFERENCES ON TABLE public.sales_department_lines TO service_role;
GRANT TRIGGER ON TABLE public.sales_department_lines TO service_role;
GRANT TRUNCATE ON TABLE public.sales_department_lines TO service_role;
GRANT REFERENCES ON TABLE public.sales_entries TO anon;
GRANT TRIGGER ON TABLE public.sales_entries TO anon;
GRANT TRUNCATE ON TABLE public.sales_entries TO anon;
GRANT DELETE ON TABLE public.sales_entries TO authenticated;
GRANT INSERT ON TABLE public.sales_entries TO authenticated;
GRANT REFERENCES ON TABLE public.sales_entries TO authenticated;
GRANT SELECT ON TABLE public.sales_entries TO authenticated;
GRANT TRIGGER ON TABLE public.sales_entries TO authenticated;
GRANT TRUNCATE ON TABLE public.sales_entries TO authenticated;
GRANT UPDATE ON TABLE public.sales_entries TO authenticated;
GRANT REFERENCES ON TABLE public.sales_entries TO service_role;
GRANT TRIGGER ON TABLE public.sales_entries TO service_role;
GRANT TRUNCATE ON TABLE public.sales_entries TO service_role;
GRANT REFERENCES ON TABLE public.schedule_weeks TO anon;
GRANT TRIGGER ON TABLE public.schedule_weeks TO anon;
GRANT TRUNCATE ON TABLE public.schedule_weeks TO anon;
GRANT DELETE ON TABLE public.schedule_weeks TO authenticated;
GRANT INSERT ON TABLE public.schedule_weeks TO authenticated;
GRANT REFERENCES ON TABLE public.schedule_weeks TO authenticated;
GRANT SELECT ON TABLE public.schedule_weeks TO authenticated;
GRANT TRIGGER ON TABLE public.schedule_weeks TO authenticated;
GRANT TRUNCATE ON TABLE public.schedule_weeks TO authenticated;
GRANT UPDATE ON TABLE public.schedule_weeks TO authenticated;
GRANT REFERENCES ON TABLE public.schedule_weeks TO service_role;
GRANT TRIGGER ON TABLE public.schedule_weeks TO service_role;
GRANT TRUNCATE ON TABLE public.schedule_weeks TO service_role;
GRANT REFERENCES ON TABLE public.shifts TO anon;
GRANT TRIGGER ON TABLE public.shifts TO anon;
GRANT TRUNCATE ON TABLE public.shifts TO anon;
GRANT DELETE ON TABLE public.shifts TO authenticated;
GRANT INSERT ON TABLE public.shifts TO authenticated;
GRANT REFERENCES ON TABLE public.shifts TO authenticated;
GRANT SELECT ON TABLE public.shifts TO authenticated;
GRANT TRIGGER ON TABLE public.shifts TO authenticated;
GRANT TRUNCATE ON TABLE public.shifts TO authenticated;
GRANT UPDATE ON TABLE public.shifts TO authenticated;
GRANT REFERENCES ON TABLE public.shifts TO service_role;
GRANT TRIGGER ON TABLE public.shifts TO service_role;
GRANT TRUNCATE ON TABLE public.shifts TO service_role;
GRANT REFERENCES ON TABLE public.stocktake_lines TO anon;
GRANT TRIGGER ON TABLE public.stocktake_lines TO anon;
GRANT TRUNCATE ON TABLE public.stocktake_lines TO anon;
GRANT DELETE ON TABLE public.stocktake_lines TO authenticated;
GRANT INSERT ON TABLE public.stocktake_lines TO authenticated;
GRANT REFERENCES ON TABLE public.stocktake_lines TO authenticated;
GRANT SELECT ON TABLE public.stocktake_lines TO authenticated;
GRANT TRIGGER ON TABLE public.stocktake_lines TO authenticated;
GRANT TRUNCATE ON TABLE public.stocktake_lines TO authenticated;
GRANT UPDATE ON TABLE public.stocktake_lines TO authenticated;
GRANT REFERENCES ON TABLE public.stocktake_lines TO service_role;
GRANT TRIGGER ON TABLE public.stocktake_lines TO service_role;
GRANT TRUNCATE ON TABLE public.stocktake_lines TO service_role;
GRANT REFERENCES ON TABLE public.stocktakes TO anon;
GRANT TRIGGER ON TABLE public.stocktakes TO anon;
GRANT TRUNCATE ON TABLE public.stocktakes TO anon;
GRANT DELETE ON TABLE public.stocktakes TO authenticated;
GRANT INSERT ON TABLE public.stocktakes TO authenticated;
GRANT REFERENCES ON TABLE public.stocktakes TO authenticated;
GRANT SELECT ON TABLE public.stocktakes TO authenticated;
GRANT TRIGGER ON TABLE public.stocktakes TO authenticated;
GRANT TRUNCATE ON TABLE public.stocktakes TO authenticated;
GRANT UPDATE ON TABLE public.stocktakes TO authenticated;
GRANT REFERENCES ON TABLE public.stocktakes TO service_role;
GRANT TRIGGER ON TABLE public.stocktakes TO service_role;
GRANT TRUNCATE ON TABLE public.stocktakes TO service_role;
GRANT DELETE ON TABLE public.subscriptions TO authenticated;
GRANT INSERT ON TABLE public.subscriptions TO authenticated;
GRANT REFERENCES ON TABLE public.subscriptions TO authenticated;
GRANT SELECT ON TABLE public.subscriptions TO authenticated;
GRANT TRIGGER ON TABLE public.subscriptions TO authenticated;
GRANT TRUNCATE ON TABLE public.subscriptions TO authenticated;
GRANT UPDATE ON TABLE public.subscriptions TO authenticated;
GRANT REFERENCES ON TABLE public.subscriptions TO service_role;
GRANT TRIGGER ON TABLE public.subscriptions TO service_role;
GRANT TRUNCATE ON TABLE public.subscriptions TO service_role;
GRANT REFERENCES ON TABLE public.supplier_ai_profiles TO anon;
GRANT TRIGGER ON TABLE public.supplier_ai_profiles TO anon;
GRANT TRUNCATE ON TABLE public.supplier_ai_profiles TO anon;
GRANT REFERENCES ON TABLE public.supplier_ai_profiles TO authenticated;
GRANT TRIGGER ON TABLE public.supplier_ai_profiles TO authenticated;
GRANT TRUNCATE ON TABLE public.supplier_ai_profiles TO authenticated;
GRANT REFERENCES ON TABLE public.supplier_ai_profiles TO service_role;
GRANT TRIGGER ON TABLE public.supplier_ai_profiles TO service_role;
GRANT TRUNCATE ON TABLE public.supplier_ai_profiles TO service_role;
GRANT REFERENCES ON TABLE public.supplier_delivery_schedules TO anon;
GRANT TRIGGER ON TABLE public.supplier_delivery_schedules TO anon;
GRANT TRUNCATE ON TABLE public.supplier_delivery_schedules TO anon;
GRANT REFERENCES ON TABLE public.supplier_delivery_schedules TO authenticated;
GRANT TRIGGER ON TABLE public.supplier_delivery_schedules TO authenticated;
GRANT TRUNCATE ON TABLE public.supplier_delivery_schedules TO authenticated;
GRANT REFERENCES ON TABLE public.supplier_delivery_schedules TO service_role;
GRANT TRIGGER ON TABLE public.supplier_delivery_schedules TO service_role;
GRANT TRUNCATE ON TABLE public.supplier_delivery_schedules TO service_role;
GRANT REFERENCES ON TABLE public.supplier_merges TO anon;
GRANT TRIGGER ON TABLE public.supplier_merges TO anon;
GRANT TRUNCATE ON TABLE public.supplier_merges TO anon;
GRANT REFERENCES ON TABLE public.supplier_merges TO authenticated;
GRANT TRIGGER ON TABLE public.supplier_merges TO authenticated;
GRANT TRUNCATE ON TABLE public.supplier_merges TO authenticated;
GRANT REFERENCES ON TABLE public.supplier_merges TO service_role;
GRANT TRIGGER ON TABLE public.supplier_merges TO service_role;
GRANT TRUNCATE ON TABLE public.supplier_merges TO service_role;
GRANT REFERENCES ON TABLE public.supplier_product_mappings TO anon;
GRANT TRIGGER ON TABLE public.supplier_product_mappings TO anon;
GRANT TRUNCATE ON TABLE public.supplier_product_mappings TO anon;
GRANT REFERENCES ON TABLE public.supplier_product_mappings TO authenticated;
GRANT SELECT ON TABLE public.supplier_product_mappings TO authenticated;
GRANT TRIGGER ON TABLE public.supplier_product_mappings TO authenticated;
GRANT TRUNCATE ON TABLE public.supplier_product_mappings TO authenticated;
GRANT REFERENCES ON TABLE public.supplier_product_mappings TO service_role;
GRANT TRIGGER ON TABLE public.supplier_product_mappings TO service_role;
GRANT TRUNCATE ON TABLE public.supplier_product_mappings TO service_role;
GRANT REFERENCES ON TABLE public.supplier_product_split_rule_lines TO anon;
GRANT TRIGGER ON TABLE public.supplier_product_split_rule_lines TO anon;
GRANT TRUNCATE ON TABLE public.supplier_product_split_rule_lines TO anon;
GRANT REFERENCES ON TABLE public.supplier_product_split_rule_lines TO authenticated;
GRANT TRIGGER ON TABLE public.supplier_product_split_rule_lines TO authenticated;
GRANT TRUNCATE ON TABLE public.supplier_product_split_rule_lines TO authenticated;
GRANT REFERENCES ON TABLE public.supplier_product_split_rule_lines TO service_role;
GRANT TRIGGER ON TABLE public.supplier_product_split_rule_lines TO service_role;
GRANT TRUNCATE ON TABLE public.supplier_product_split_rule_lines TO service_role;
GRANT REFERENCES ON TABLE public.supplier_product_split_rules TO anon;
GRANT TRIGGER ON TABLE public.supplier_product_split_rules TO anon;
GRANT TRUNCATE ON TABLE public.supplier_product_split_rules TO anon;
GRANT REFERENCES ON TABLE public.supplier_product_split_rules TO authenticated;
GRANT TRIGGER ON TABLE public.supplier_product_split_rules TO authenticated;
GRANT TRUNCATE ON TABLE public.supplier_product_split_rules TO authenticated;
GRANT REFERENCES ON TABLE public.supplier_product_split_rules TO service_role;
GRANT TRIGGER ON TABLE public.supplier_product_split_rules TO service_role;
GRANT TRUNCATE ON TABLE public.supplier_product_split_rules TO service_role;
GRANT REFERENCES ON TABLE public.suppliers TO anon;
GRANT TRIGGER ON TABLE public.suppliers TO anon;
GRANT TRUNCATE ON TABLE public.suppliers TO anon;
GRANT DELETE ON TABLE public.suppliers TO authenticated;
GRANT INSERT ON TABLE public.suppliers TO authenticated;
GRANT REFERENCES ON TABLE public.suppliers TO authenticated;
GRANT SELECT ON TABLE public.suppliers TO authenticated;
GRANT TRIGGER ON TABLE public.suppliers TO authenticated;
GRANT TRUNCATE ON TABLE public.suppliers TO authenticated;
GRANT UPDATE ON TABLE public.suppliers TO authenticated;
GRANT REFERENCES ON TABLE public.suppliers TO service_role;
GRANT TRIGGER ON TABLE public.suppliers TO service_role;
GRANT TRUNCATE ON TABLE public.suppliers TO service_role;
GRANT REFERENCES ON TABLE public.time_off_requests TO anon;
GRANT TRIGGER ON TABLE public.time_off_requests TO anon;
GRANT TRUNCATE ON TABLE public.time_off_requests TO anon;
GRANT DELETE ON TABLE public.time_off_requests TO authenticated;
GRANT INSERT ON TABLE public.time_off_requests TO authenticated;
GRANT REFERENCES ON TABLE public.time_off_requests TO authenticated;
GRANT SELECT ON TABLE public.time_off_requests TO authenticated;
GRANT TRIGGER ON TABLE public.time_off_requests TO authenticated;
GRANT TRUNCATE ON TABLE public.time_off_requests TO authenticated;
GRANT UPDATE ON TABLE public.time_off_requests TO authenticated;
GRANT REFERENCES ON TABLE public.time_off_requests TO service_role;
GRANT TRIGGER ON TABLE public.time_off_requests TO service_role;
GRANT TRUNCATE ON TABLE public.time_off_requests TO service_role;
GRANT REFERENCES ON TABLE public.user_action_permissions TO anon;
GRANT TRIGGER ON TABLE public.user_action_permissions TO anon;
GRANT TRUNCATE ON TABLE public.user_action_permissions TO anon;
GRANT DELETE ON TABLE public.user_action_permissions TO authenticated;
GRANT INSERT ON TABLE public.user_action_permissions TO authenticated;
GRANT REFERENCES ON TABLE public.user_action_permissions TO authenticated;
GRANT SELECT ON TABLE public.user_action_permissions TO authenticated;
GRANT TRIGGER ON TABLE public.user_action_permissions TO authenticated;
GRANT TRUNCATE ON TABLE public.user_action_permissions TO authenticated;
GRANT UPDATE ON TABLE public.user_action_permissions TO authenticated;
GRANT REFERENCES ON TABLE public.user_action_permissions TO service_role;
GRANT TRIGGER ON TABLE public.user_action_permissions TO service_role;
GRANT TRUNCATE ON TABLE public.user_action_permissions TO service_role;
GRANT REFERENCES ON TABLE public.user_department_permissions TO anon;
GRANT TRIGGER ON TABLE public.user_department_permissions TO anon;
GRANT TRUNCATE ON TABLE public.user_department_permissions TO anon;
GRANT DELETE ON TABLE public.user_department_permissions TO authenticated;
GRANT INSERT ON TABLE public.user_department_permissions TO authenticated;
GRANT REFERENCES ON TABLE public.user_department_permissions TO authenticated;
GRANT SELECT ON TABLE public.user_department_permissions TO authenticated;
GRANT TRIGGER ON TABLE public.user_department_permissions TO authenticated;
GRANT TRUNCATE ON TABLE public.user_department_permissions TO authenticated;
GRANT UPDATE ON TABLE public.user_department_permissions TO authenticated;
GRANT REFERENCES ON TABLE public.user_department_permissions TO service_role;
GRANT TRIGGER ON TABLE public.user_department_permissions TO service_role;
GRANT TRUNCATE ON TABLE public.user_department_permissions TO service_role;
GRANT REFERENCES ON TABLE public.user_page_permissions TO anon;
GRANT TRIGGER ON TABLE public.user_page_permissions TO anon;
GRANT TRUNCATE ON TABLE public.user_page_permissions TO anon;
GRANT DELETE ON TABLE public.user_page_permissions TO authenticated;
GRANT INSERT ON TABLE public.user_page_permissions TO authenticated;
GRANT REFERENCES ON TABLE public.user_page_permissions TO authenticated;
GRANT SELECT ON TABLE public.user_page_permissions TO authenticated;
GRANT TRIGGER ON TABLE public.user_page_permissions TO authenticated;
GRANT TRUNCATE ON TABLE public.user_page_permissions TO authenticated;
GRANT UPDATE ON TABLE public.user_page_permissions TO authenticated;
GRANT REFERENCES ON TABLE public.user_page_permissions TO service_role;
GRANT TRIGGER ON TABLE public.user_page_permissions TO service_role;
GRANT TRUNCATE ON TABLE public.user_page_permissions TO service_role;
GRANT REFERENCES ON TABLE public.waste_entries TO anon;
GRANT TRIGGER ON TABLE public.waste_entries TO anon;
GRANT TRUNCATE ON TABLE public.waste_entries TO anon;
GRANT DELETE ON TABLE public.waste_entries TO authenticated;
GRANT INSERT ON TABLE public.waste_entries TO authenticated;
GRANT REFERENCES ON TABLE public.waste_entries TO authenticated;
GRANT SELECT ON TABLE public.waste_entries TO authenticated;
GRANT TRIGGER ON TABLE public.waste_entries TO authenticated;
GRANT TRUNCATE ON TABLE public.waste_entries TO authenticated;
GRANT UPDATE ON TABLE public.waste_entries TO authenticated;
GRANT REFERENCES ON TABLE public.waste_entries TO service_role;
GRANT TRIGGER ON TABLE public.waste_entries TO service_role;
GRANT TRUNCATE ON TABLE public.waste_entries TO service_role;
GRANT REFERENCES ON TABLE public.waste_photos TO anon;
GRANT TRIGGER ON TABLE public.waste_photos TO anon;
GRANT TRUNCATE ON TABLE public.waste_photos TO anon;
GRANT DELETE ON TABLE public.waste_photos TO authenticated;
GRANT INSERT ON TABLE public.waste_photos TO authenticated;
GRANT REFERENCES ON TABLE public.waste_photos TO authenticated;
GRANT SELECT ON TABLE public.waste_photos TO authenticated;
GRANT TRIGGER ON TABLE public.waste_photos TO authenticated;
GRANT TRUNCATE ON TABLE public.waste_photos TO authenticated;
GRANT UPDATE ON TABLE public.waste_photos TO authenticated;
GRANT REFERENCES ON TABLE public.waste_photos TO service_role;
GRANT TRIGGER ON TABLE public.waste_photos TO service_role;
GRANT TRUNCATE ON TABLE public.waste_photos TO service_role;
GRANT REFERENCES ON TABLE public.workforce_audit_log TO anon;
GRANT TRIGGER ON TABLE public.workforce_audit_log TO anon;
GRANT TRUNCATE ON TABLE public.workforce_audit_log TO anon;
GRANT DELETE ON TABLE public.workforce_audit_log TO authenticated;
GRANT INSERT ON TABLE public.workforce_audit_log TO authenticated;
GRANT REFERENCES ON TABLE public.workforce_audit_log TO authenticated;
GRANT SELECT ON TABLE public.workforce_audit_log TO authenticated;
GRANT TRIGGER ON TABLE public.workforce_audit_log TO authenticated;
GRANT TRUNCATE ON TABLE public.workforce_audit_log TO authenticated;
GRANT UPDATE ON TABLE public.workforce_audit_log TO authenticated;
GRANT REFERENCES ON TABLE public.workforce_audit_log TO service_role;
GRANT TRIGGER ON TABLE public.workforce_audit_log TO service_role;
GRANT TRUNCATE ON TABLE public.workforce_audit_log TO service_role;
GRANT REFERENCES ON TABLE public.workforce_employee_compensation TO anon;
GRANT TRIGGER ON TABLE public.workforce_employee_compensation TO anon;
GRANT TRUNCATE ON TABLE public.workforce_employee_compensation TO anon;
GRANT DELETE ON TABLE public.workforce_employee_compensation TO authenticated;
GRANT INSERT ON TABLE public.workforce_employee_compensation TO authenticated;
GRANT REFERENCES ON TABLE public.workforce_employee_compensation TO authenticated;
GRANT SELECT ON TABLE public.workforce_employee_compensation TO authenticated;
GRANT TRIGGER ON TABLE public.workforce_employee_compensation TO authenticated;
GRANT TRUNCATE ON TABLE public.workforce_employee_compensation TO authenticated;
GRANT UPDATE ON TABLE public.workforce_employee_compensation TO authenticated;
GRANT REFERENCES ON TABLE public.workforce_employee_compensation TO service_role;
GRANT TRIGGER ON TABLE public.workforce_employee_compensation TO service_role;
GRANT TRUNCATE ON TABLE public.workforce_employee_compensation TO service_role;
GRANT REFERENCES ON TABLE public.workforce_employees TO anon;
GRANT TRIGGER ON TABLE public.workforce_employees TO anon;
GRANT TRUNCATE ON TABLE public.workforce_employees TO anon;
GRANT DELETE ON TABLE public.workforce_employees TO authenticated;
GRANT INSERT ON TABLE public.workforce_employees TO authenticated;
GRANT REFERENCES ON TABLE public.workforce_employees TO authenticated;
GRANT SELECT ON TABLE public.workforce_employees TO authenticated;
GRANT TRIGGER ON TABLE public.workforce_employees TO authenticated;
GRANT TRUNCATE ON TABLE public.workforce_employees TO authenticated;
GRANT UPDATE ON TABLE public.workforce_employees TO authenticated;
GRANT REFERENCES ON TABLE public.workforce_employees TO service_role;
GRANT TRIGGER ON TABLE public.workforce_employees TO service_role;
GRANT TRUNCATE ON TABLE public.workforce_employees TO service_role;
GRANT REFERENCES ON TABLE public.workforce_permission_set_permissions TO anon;
GRANT TRIGGER ON TABLE public.workforce_permission_set_permissions TO anon;
GRANT TRUNCATE ON TABLE public.workforce_permission_set_permissions TO anon;
GRANT DELETE ON TABLE public.workforce_permission_set_permissions TO authenticated;
GRANT INSERT ON TABLE public.workforce_permission_set_permissions TO authenticated;
GRANT REFERENCES ON TABLE public.workforce_permission_set_permissions TO authenticated;
GRANT SELECT ON TABLE public.workforce_permission_set_permissions TO authenticated;
GRANT TRIGGER ON TABLE public.workforce_permission_set_permissions TO authenticated;
GRANT TRUNCATE ON TABLE public.workforce_permission_set_permissions TO authenticated;
GRANT UPDATE ON TABLE public.workforce_permission_set_permissions TO authenticated;
GRANT REFERENCES ON TABLE public.workforce_permission_set_permissions TO service_role;
GRANT TRIGGER ON TABLE public.workforce_permission_set_permissions TO service_role;
GRANT TRUNCATE ON TABLE public.workforce_permission_set_permissions TO service_role;
GRANT REFERENCES ON TABLE public.workforce_permission_sets TO anon;
GRANT TRIGGER ON TABLE public.workforce_permission_sets TO anon;
GRANT TRUNCATE ON TABLE public.workforce_permission_sets TO anon;
GRANT DELETE ON TABLE public.workforce_permission_sets TO authenticated;
GRANT INSERT ON TABLE public.workforce_permission_sets TO authenticated;
GRANT REFERENCES ON TABLE public.workforce_permission_sets TO authenticated;
GRANT SELECT ON TABLE public.workforce_permission_sets TO authenticated;
GRANT TRIGGER ON TABLE public.workforce_permission_sets TO authenticated;
GRANT TRUNCATE ON TABLE public.workforce_permission_sets TO authenticated;
GRANT UPDATE ON TABLE public.workforce_permission_sets TO authenticated;
GRANT REFERENCES ON TABLE public.workforce_permission_sets TO service_role;
GRANT TRIGGER ON TABLE public.workforce_permission_sets TO service_role;
GRANT TRUNCATE ON TABLE public.workforce_permission_sets TO service_role;
GRANT REFERENCES ON TABLE public.workforce_settings TO anon;
GRANT TRIGGER ON TABLE public.workforce_settings TO anon;
GRANT TRUNCATE ON TABLE public.workforce_settings TO anon;
GRANT DELETE ON TABLE public.workforce_settings TO authenticated;
GRANT INSERT ON TABLE public.workforce_settings TO authenticated;
GRANT REFERENCES ON TABLE public.workforce_settings TO authenticated;
GRANT SELECT ON TABLE public.workforce_settings TO authenticated;
GRANT TRIGGER ON TABLE public.workforce_settings TO authenticated;
GRANT TRUNCATE ON TABLE public.workforce_settings TO authenticated;
GRANT UPDATE ON TABLE public.workforce_settings TO authenticated;
GRANT REFERENCES ON TABLE public.workforce_settings TO service_role;
GRANT TRIGGER ON TABLE public.workforce_settings TO service_role;
GRANT TRUNCATE ON TABLE public.workforce_settings TO service_role;
GRANT REFERENCES ON TABLE public.workforce_timecards TO anon;
GRANT TRIGGER ON TABLE public.workforce_timecards TO anon;
GRANT TRUNCATE ON TABLE public.workforce_timecards TO anon;
GRANT DELETE ON TABLE public.workforce_timecards TO authenticated;
GRANT INSERT ON TABLE public.workforce_timecards TO authenticated;
GRANT REFERENCES ON TABLE public.workforce_timecards TO authenticated;
GRANT SELECT ON TABLE public.workforce_timecards TO authenticated;
GRANT TRIGGER ON TABLE public.workforce_timecards TO authenticated;
GRANT TRUNCATE ON TABLE public.workforce_timecards TO authenticated;
GRANT UPDATE ON TABLE public.workforce_timecards TO authenticated;
GRANT REFERENCES ON TABLE public.workforce_timecards TO service_role;
GRANT TRIGGER ON TABLE public.workforce_timecards TO service_role;
GRANT TRUNCATE ON TABLE public.workforce_timecards TO service_role;
COMMIT;
