import {
  formatReportDate,
  formatReportDateTime,
  formatReportMoney,
  formatReportQuantity,
  stocktakeReportFileName,
} from "./stocktakeReportData.js";

const colors = {
  bg: [15, 23, 42],
  card: [248, 250, 252],
  primary: [59, 130, 246],
  line: [203, 213, 225],
  muted: [100, 116, 139],
  text: [15, 23, 42],
  white: [255, 255, 255],
};

function addFooter(doc) {
  const pageCount = doc.getNumberOfPages();
  const width = doc.internal.pageSize.getWidth();
  const height = doc.internal.pageSize.getHeight();
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setDrawColor(...colors.line);
    doc.line(40, height - 34, width - 40, height - 34);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...colors.muted);
    doc.text("Generated by MarginFlow", 40, height - 18);
    doc.text(`Page ${page} of ${pageCount}`, width - 40, height - 18, { align: "right" });
  }
}

function drawCoverHeader(doc, report) {
  doc.setFillColor(...colors.bg);
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 132, "F");
  doc.setFillColor(...colors.primary);
  doc.roundedRect(40, 36, 44, 44, 6, 6, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...colors.white);
  doc.text("MF", 62, 64, { align: "center" });

  doc.setFontSize(12);
  doc.text(report.companyName, 98, 50);
  doc.setFontSize(24);
  doc.text("Stocktake Report", 98, 79);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(203, 213, 225);
  doc.text(`Stocktake date: ${formatReportDate(report.stocktakeDate)}`, 98, 100);
  doc.text(`Generated: ${formatReportDateTime(report.generatedAt)}`, 98, 116);
}

function summaryRows(report) {
  const rows = [
    ["Total stock value", formatReportMoney(report.grandTotal, report.currency)],
    ["Number of counted products", report.productCount],
    ["Total preparation/prep value", formatReportMoney(report.preparationTotal, report.currency)],
    ["Product stock subtotal", formatReportMoney(report.productStockTotal, report.currency)],
  ];
  if (report.zeroQuantityCount) rows.splice(2, 0, ["Products with zero quantity", report.zeroQuantityCount]);
  if (report.newProductCount) rows.splice(3, 0, ["New products without a Product ID", report.newProductCount]);
  return rows;
}

function drawSectionTitle(doc, title, y) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...colors.text);
  doc.text(title, 40, y);
}

function addTotalsBlock(doc, report, startY) {
  const pageHeight = doc.internal.pageSize.getHeight();
  let y = startY;
  if (y > pageHeight - 120) {
    doc.addPage();
    y = 54;
  }
  doc.setFillColor(...colors.card);
  doc.setDrawColor(...colors.line);
  doc.roundedRect(340, y, 215, 82, 5, 5, "FD");
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...colors.muted);
  doc.text("Product stock subtotal", 354, y + 22);
  doc.text("Preparation subtotal", 354, y + 43);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...colors.text);
  doc.text(formatReportMoney(report.productStockTotal, report.currency), 540, y + 22, { align: "right" });
  doc.text(formatReportMoney(report.preparationTotal, report.currency), 540, y + 43, { align: "right" });
  doc.setDrawColor(...colors.line);
  doc.line(354, y + 54, 540, y + 54);
  doc.setFontSize(12);
  doc.text("Grand total", 354, y + 72);
  doc.text(formatReportMoney(report.grandTotal, report.currency), 540, y + 72, { align: "right" });
}

export async function downloadStocktakePdf(report) {
  const [{ jsPDF }, autoTableModule] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable"),
  ]);
  const autoTable = autoTableModule.default || autoTableModule.autoTable;
  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "a4" });

  drawCoverHeader(doc, report);

  autoTable(doc, {
    startY: 156,
    head: [["Summary", "Value"]],
    body: summaryRows(report),
    theme: "grid",
    headStyles: { fillColor: colors.primary, textColor: colors.white, fontStyle: "bold" },
    styles: { font: "helvetica", fontSize: 9, cellPadding: 7, lineColor: colors.line },
    columnStyles: { 1: { halign: "right", fontStyle: "bold" } },
    margin: { left: 40, right: 40 },
    rowPageBreak: "avoid",
  });

  let y = doc.lastAutoTable.finalY + 26;
  drawSectionTitle(doc, "Department Summary", y);
  autoTable(doc, {
    startY: y + 10,
    head: [["Department", "Products", "Stock value", "% of total stock"]],
    body: report.departments.map((department) => [
      department.department,
      `${department.productCount} products`,
      formatReportMoney(department.stockValue, report.currency),
      `${department.percentageOfTotal.toFixed(1)}%`,
    ]),
    theme: "striped",
    headStyles: { fillColor: colors.bg, textColor: colors.white, fontStyle: "bold" },
    styles: { font: "helvetica", fontSize: 8.5, cellPadding: 6 },
    columnStyles: { 1: { halign: "right" }, 2: { halign: "right" }, 3: { halign: "right" } },
    margin: { left: 40, right: 40 },
    rowPageBreak: "avoid",
  });

  y = doc.lastAutoTable.finalY + 28;
  drawSectionTitle(doc, "Detailed Stock", y);
  autoTable(doc, {
    startY: y + 10,
    head: [["Product", "Quantity", "Pack Size / Unit", "Unit Cost", "Total Value", "Supplier", "Department"]],
    body: report.products.map((line) => [
      line.productName,
      formatReportQuantity(line.quantity),
      line.packSize,
      formatReportMoney(line.unitCost, report.currency),
      formatReportMoney(line.totalValue, report.currency),
      line.supplier,
      line.department,
    ]),
    theme: "grid",
    headStyles: { fillColor: colors.bg, textColor: colors.white, fontStyle: "bold" },
    styles: { font: "helvetica", fontSize: 7.2, cellPadding: 4.5, lineColor: colors.line, overflow: "linebreak" },
    columnStyles: {
      0: { cellWidth: 118 },
      1: { cellWidth: 42, halign: "right" },
      2: { cellWidth: 65 },
      3: { cellWidth: 55, halign: "right" },
      4: { cellWidth: 60, halign: "right" },
      5: { cellWidth: 82 },
      6: { cellWidth: 70 },
    },
    margin: { left: 40, right: 40 },
    rowPageBreak: "avoid",
  });

  if (report.preparationItems.length) {
    y = doc.lastAutoTable.finalY + 28;
    drawSectionTitle(doc, "Preparation Stock", y);
    autoTable(doc, {
      startY: y + 10,
      head: [["Preparation Area", "Quantity", "Unit Cost", "Total Value"]],
      body: report.preparationItems.map((line) => [
        line.productName,
        formatReportQuantity(line.quantity),
        formatReportMoney(line.unitCost, report.currency),
        formatReportMoney(line.totalValue, report.currency),
      ]),
      theme: "grid",
      headStyles: { fillColor: colors.primary, textColor: colors.white, fontStyle: "bold" },
      styles: { font: "helvetica", fontSize: 8.5, cellPadding: 5, lineColor: colors.line },
      columnStyles: { 1: { halign: "right" }, 2: { halign: "right" }, 3: { halign: "right" } },
      margin: { left: 40, right: 40 },
      rowPageBreak: "avoid",
    });
  }

  addTotalsBlock(doc, report, doc.lastAutoTable.finalY + 24);
  addFooter(doc);
  doc.save(stocktakeReportFileName(report, "pdf"));
}
